version: '3'

services:
  web:
    image: jrobinsonc/wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
    depends_on:
      - db

  db:
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
    ports:
      - 3306:3306

volumes:
  db-data:
